service:
  name: slss-offline-lambda-example


plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  stage: 'development'
  region: 'us-west-1'
  profile: default
  role: {replace rol execution lambda}


functions:
  exampleFunc:
    handler: src/lambda.handler
    events:
      - http:
          path: /
          method: get
          cors: true
          integration: lambda
          request:
            passThrough: NEVER
#           the "template" is not recognized by serverless-offline, see: https://github.com/dherault/serverless-offline/blob/a878917640d624347d76fd14bb3e9ad5799cbcaf/src/Endpoint.js#L31
            template:
              application/json: "#set( $body = $input.json(\"$\") )\n\n    \n  #define( $loop )\n    {\n    #foreach($key in $map.keySet())\n        #set( $k = $util.escapeJavaScript($key) )\n        #set( $v = $util.escapeJavaScript($map.get($key)).replaceAll(\"\\\\'\", \"'\") )\n        \"$k\":\n          \"$v\"\n          #if( $foreach.hasNext ) , #end\n    #end\n    }\n  #end\n\n  {\n    \"body\": $body,\n    \"method\": \"$context.httpMethod\",\n    \"principalId\": \"$context.authorizer.principalId\",\n    \"stage\": \"$context.stage\",\n\n    \"cognitoPoolClaims\" : {\n       \n       \"sub\": \"$context.authorizer.claims.sub\"\n    },\n\n    #set( $map = $context.authorizer )\n    \"enhancedAuthContext\": $loop,\n    #set( $map = $input.params().header )\n    \"headers\": $loop,\n\n    #set( $map = $input.params().querystring )\n    \"query\": $loop,\n\n    #set( $map = $input.params().path )\n    \"path\": $loop,\n\n    #set( $map = $context.identity )\n    \"identity\": $loop,\n    #set( $map = $stageVariables )\n    \"stageVariables\": $loop,\n    \"requestPath\": \"$context.resourcePath\"\n  }"
#          the "response" is not recognized by serverless-offline, see: https://github.com/dherault/serverless-offline/blob/a878917640d624347d76fd14bb3e9ad5799cbcaf/src/Endpoint.js#L55
          response:
            #template: $input.path('$')
            #template: "#set ($errorObj = $util.parseJson($input.path(\"$\")))\n{\n\"success\": \"$errorObj.success\",\n\"message\":\"$errorObj.message\",\n\"errors\":\"$errorObj.errors\"\n}"
            template: ${file(successResponse.template)}
            headers:
              Content-Type: "'application/json'"
            statusCodes:
              200:
                pattern: ''
              500:
                pattern: '.*500.*'
                #template: "#set ($errorObj = $util.parseJson($input.path(\"$.errorMessage\")))\n{\n\"success\": \"$errorObj.success\",\n\"message\":\"$errorObj.message\",\n\"errors\":\"$errorObj.errors\"\n}"
                template: ${file(errorResponse.template)}
                headers:
                  Content-Type: "'application/json'"
              400:
                pattern: '.*400.*'
                #template: "#set ($errorObj = $util.parseJson($input.path(\"$.errorMessage\")))\n{\n\"success\": \"$errorObj.success\",\n\"message\":\"$errorObj.message\",\n\"errors\":\"$errorObj.errors\"\n}"
                template: ${file(errorResponse.template)}
                headers:
                  Content-Type: "'application/json'"
